MyBlog/MyBlog/ViewModels/PostsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MyBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBlog.ViewModels
{
    public class PostsViewModel
    {
        public List<Post>Posts { get; set; }
        public PageViewModel Paginator { get; set; }
        public SelectList Categories { get; set; }
    }
}

MyBlog/MyBlog/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyBlog.Data;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CommentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comments
        public async Task<IActionResult> Index(/*annex*/ int? id)
        {
            //annex
            if (id !=null)
            {
                var post = await _context.Posts.Where(p => p.Id == id)
                    .FirstOrDefaultAsync();
                ViewBag.Post = post;

                var comments = await _context.Comments
                    .Include(c => c.ApplicationUser)
                    .Include(c => c.Post)
                    .Where(c => c.PostId == id)
                    .ToListAsync();
                return View(comments);
            }
            
            //original
            var applicationDbContext = _context.Comments.Include(c => c.Post);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Post)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        [Authorize]
        public IActionResult Create(/*annex*/int? postId)
        {
            //annex
            var post = _context.Posts.Where(p => p.Id == postId).FirstOrDefault();
            ViewBag.Post = post;

            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]        
        public async Task<IActionResult> Create([Bind("Id,Content,PublishDate,PublishTime,ApplicationUserId,ApplicationUserName,PostId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                var user = await _context.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefaultAsync();
                comment.ApplicationUserId = user.Id;
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id=comment.PostId});
            }
            return View(comment);

            //original
            //if (ModelState.IsValid)
            //{
            //    _context.Add(comment);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["PostId"] = new SelectList(_context.Posts, "Id", "Content", comment.PostId);
            //return View(comment);
        }

        // GET: Comments/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);          

            if (comment == null)
            {
                return NotFound();
            }

            //annex Вариант ограничения доступа внутри кода контроллера c редирект на страницу отказа
            if (comment.ApplicationUserName == User.Identity.Name)
            {
                //ViewData["PostId"] = new SelectList(_context.Posts, "Id", "Content", comment.PostId);
                ViewBag.PostId = comment.PostId;
                return View(comment);
            }

            return Redirect("/Identity/Account/AccessDenied");

            //в оригинале заканчиваллось просто так, там где аннекс начинается.
            //ViewData["PostId"] = new SelectList(_context.Posts, "Id", "Content", comment.PostId);
            //return View(comment);

        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Content,PublishDate,PublishTime,ApplicationUserId,PostId,ApplicationUserName")] Comment comment)
        {
            if (id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), /*annex*/ new { id = comment.PostId });
            }
            //ViewData["PostId"] = new SelectList(_context.Posts, "Id", "Content", comment.PostId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Post)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            //annex Вариант ограничения доступа внутри кода контроллера c редирект на страницу отказа
            if (comment.ApplicationUserName == User.Identity.Name)
                return View(comment);
            
            return Redirect("/Identity/Account/AccessDenied");

            //в оригинале заканчиваллось просто так, там где аннекс начинается.
            //return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _context.Comments.FindAsync(id);
            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), /*annex*/new { id = comment.PostId } );
        }

        private bool CommentExists(int id)
        {
            return _context.Comments.Any(e => e.Id == id);
        }
    }
}

MyBlog/MyBlog/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyBlog.Data;
using MyBlog.Models;
using MyBlog.ViewModels;

namespace MyBlog.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        //annex
        private IWebHostEnvironment _env;
        //annex2 - расширение для аплоуда, но можно и без него
        private readonly string[] permittedExtensios = new string[]
        {
            ".jpg", ".jpeg", ".png", ".bmp", ".gif"
        };

        public PostsController(ApplicationDbContext context, /*annex*/IWebHostEnvironment env)
        {
            _context = context;

            //annex
            _env = env;
        }

        // GET: Posts
        public async Task<IActionResult> Index(/*annex*/ int categoryId=0, int pageNumber=1)
        {
            


            //annex
            //1 - Формирование коллекции выводимых постов
            var posts = _context.Posts.ToList();

            //session remastered
            if (categoryId == 0)
            {
                if (HttpContext.Session.GetInt32("cat_id") != null)
                    categoryId = (int)HttpContext.Session.GetInt32("cat_id");
            }
            else if (categoryId > 0)
            {
                HttpContext.Session.SetInt32("cat_id", categoryId);
            }

            if (categoryId != 0)
                posts = posts.Where(p => p.CategoryId == categoryId).ToList();

            //2 - Разбивка коллекции постов на страницы пагинации
            int pageSize = 3;
            int count = posts.Count;
            var items = posts
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize).ToList();

            //3 - Формирование коллекции категорий для создания фильтра
            List<Category> categories = await _context.Categories.ToListAsync();
            //categories.Insert(0, new Category() { Id = 0, Name = "All categories" });

            //4 - Создание менеджера пагинации
            PageViewModel paginator = new PageViewModel(count, pageNumber, pageSize);

            //5 - Создание модели представления постов
            PostsViewModel viewModel = new PostsViewModel()
            {
                Posts = items,
                Paginator = paginator,
                Categories = new SelectList(categories, "Id", "Name", "test")
            };

            return View(viewModel);            

            //original
            //return View(await _context.Posts.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        // annex. Authorize - предотвращает несанкционированный доступ.
        [Authorize(Roles ="SuperAdmin")]
        public IActionResult Create()
        {
            //annex for selectlist categories
            var categories = _context.Categories.ToList();
            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name");
            
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //original
        //public async Task<IActionResult> Create([Bind("id,Title,Description,Content,PublishDate,PublishTime,ImagePath")] Post post)
        
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Content,PublishDate,PublishTime,ImagePath, CategoryId")] Post post,
            /*annex*/ IFormFile uploadFile)
        {
            if (ModelState.IsValid)
            {
                if (uploadFile !=null)
                {
                    string name = uploadFile.FileName;
                    var ext = Path.GetExtension(name);
                    if (permittedExtensios.Contains(ext))
                    {
                        string path = $"/files/{name}";
                        string serverPath = _env.WebRootPath + path;
                        using (FileStream fs = new FileStream(serverPath, FileMode.Create, FileAccess.Write))
                        {
                            await uploadFile.CopyToAsync(fs);
                        }
                        post.ImagePath = path;

                        _context.Posts.Add(post);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return RedirectToAction("ExtensionsError", "Errors");
                    }
                }   
                else
                {
                    return RedirectToAction("Upload", "Errors");
                }
            }

            //annex SelectList categories
            var categories = _context.Categories.ToList();
            ViewData["categoryId"] = new SelectList(categories, "Id", "Name", post.CategoryId);

            return View(post);


            //original
            //if (ModelState.IsValid)
            //{
            //    _context.Add(post);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //return View(post);
        }

        // GET: Posts/Edit/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }

            //annex for selectlist categories
            var categories = _context.Categories.ToList();
            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name");
            //ViewData["SelectCategoryId"] = post.CategoryId;

            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Content,PublishDate,PublishTime,ImagePath")] Post post)
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Content,PublishDate,PublishTime,ImagePath, CategoryId")] Post post,
            IFormFile uploadFile)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string oldImagePath = _context.Posts.Where(p => p.Id == id)
                                .AsNoTracking()
                                .FirstOrDefault().ImagePath;

                    if (uploadFile==null)
                    {
                        post.ImagePath = oldImagePath;
                    }

                    if (uploadFile!=null)
                    {
                        string name = uploadFile.FileName;
                        string path = $"/files/{name}";
                        var ext = Path.GetExtension(name);
                        if (permittedExtensios.Contains(ext))
                        {
                            string serverPath = _env.WebRootPath + path;
                            using (FileStream fs = new FileStream(serverPath, FileMode.Create, FileAccess.Write))
                            {
                                await uploadFile.CopyToAsync(fs);
                            }
                            post.ImagePath = path;
                            string oldServerPath = _env.WebRootPath + oldImagePath;
                            System.IO.File.Delete(oldServerPath);                            
                        }
                        else
                        {
                            return RedirectToAction("ExtensionsError", "Errors");
                        }
                    }

                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), /*annex*/ new { categoryId = post.CategoryId });
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5

MyBlog/MyBlog/Views/Posts/Create.cshtml
@model MyBlog.Models.Post

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @*<form asp-action="Create">*@
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                @*<input asp-for="Description" class="form-control" />*@
                <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                @*<input asp-for="Content" class="form-control" />*@
                <textarea asp-for="Content" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishDate" class="control-label"></label>
                <input asp-for="PublishDate" class="form-control" />
                <span asp-validation-for="PublishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishTime" class="control-label"></label>
                <input asp-for="PublishTime" class="form-control" />
                <span asp-validation-for="PublishTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                @*<input asp-for="ImagePath" class="form-control" />*@
                <input asp-for="ImagePath" type="file" name="uploadFile" accept="image/*" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>

            @*annex for selectlist categories*@
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" asp-items="ViewBag.CategoryId" class="form-control"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyBlog/MyBlog/Views/Posts/Delete.cshtml
@model MyBlog.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyBlog/MyBlog/Views/Posts/Details.cshtml
@model MyBlog.Models.Post

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Post</h4>
    <hr />
    <div class="row">
        <div class="col-sm-4">
            <img src="@Model.ImagePath" width="250"/>
        </div>
        <div class="col-sm-8">
            <dl class="row">
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Content)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Content)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.PublishDate)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.PublishDate)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.PublishTime)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.PublishTime)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.ImagePath)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.ImagePath)
                </dd>
            </dl>
        </div>
    </div>    
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyBlog/MyBlog/Views/Posts/Edit.cshtml
@model MyBlog.Models.Post

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @*<form asp-action="Edit">*@
        <form asp-action="Edit" enctype="multipart/form-data">

            <!---->
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PublishDate" class="control-label"></label>
                <input asp-for="PublishDate" class="form-control" />
                <span asp-validation-for="PublishDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PublishTime" class="control-label"></label>
                <input asp-for="PublishTime" class="form-control" />
                <span asp-validation-for="PublishTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                @*<input asp-for="ImagePath" class="form-control" />*@
                <input asp-for="ImagePath" type="file" name="uploadFile" accept="image/*" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>

            @*annex for selectlist categories*@
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" asp-items="ViewBag.CategoryId" class="form-control"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyBlog/MyBlog/Views/Posts/Index.cshtml
@*@model IEnumerable<MyBlog.Models.Post>*@
@model MyBlog.ViewModels.PostsViewModel
@addTagHelper *, MyBlog
@*так подключается тагхелпер, указание название приложения после звездочки и запятой необходимо*@

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@*annex. Simple autorization*@
@*@if (User.Identity.Name == "admin123@ukr.net")
    {
        <p>
            <a asp-action="Create">Create New</a>
        </p>
    }*@

@*annex. Role autorization*@
@if (User.IsInRole("SuperAdmin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

@*annex for selectlist*@
<form method="get">
    <div class="form-inline form-group">
        <label class="control-label"> Category </label>
        &nbsp;&nbsp;&nbsp;
        <select name="categoryId" asp-items="Model.Categories" selectedItem class="form-control"></select>
        &nbsp;&nbsp;&nbsp;
        <input type="submit" value="Select" class="btn btn-primary" />
    </div>
</form>

@foreach (var item in Model.Posts)
{
    <div class="card card_margin">
        <div class="card-header">
            @Html.DisplayFor(modelItem => item.PublishDate)
            @Html.DisplayFor(modelItem => item.PublishTime)
        </div>
        <div class="card-body">
            <img src="@Html.DisplayFor(modelItem => item.ImagePath)" alt="..." class="post_image" />
            <h5 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h5>
            <h6 class="card-title">Категория: @Html.DisplayFor(modelItem => item.Category.Name)</h6>
            <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>
            <p class="card-text">@Html.DisplayFor(modelItem => item.Content)</p>
            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
        </div>
        <div class="card-footer text-muted">
            |
            @*annex for comment*@
            <a asp-action="Index" asp-controller="Comments" asp-route-id="@item.Id">Comments</a>
            |
            @if (User.IsInRole("SuperAdmin"))
            {
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                <span>|</span>
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                <span>|</span>
            }
        </div>
    </div>

}

<br />

<page-link page-model="Model.Paginator" page-action="Index"></page-link>